#!/bin/bash

echo "📋 SUPABASE CLOUD MIGRATION INSTRUCTIONS"
echo "========================================"
echo ""
echo "Ponieważ używasz Supabase Cloud, musisz wykonać migrację ręcznie:"
echo ""
echo "1. Otwórz Supabase Dashboard: https://supabase.com/dashboard"
echo "2. Przejdź do swojego projektu"
echo "3. Idź do 'SQL Editor'"
echo "4. Skopiuj i wykonaj poniższy kod SQL:"
echo ""
echo "----------------------------------------"
cat supabase/migrations/20251011000100_location_rpc_functions.sql
echo "----------------------------------------"
echo ""
echo "5. Po wykonaniu migracji, uruchom testy:"
echo "   ./location_test_api.sh"
echo ""
echo "Alternatywnie, jeśli masz skonfigurowane Supabase CLI:"
echo "   npx supabase link --project-ref [YOUR_PROJECT_REF]"
echo "   npx supabase db push"
